version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "rails"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  pull-request-branch-name:
    separator: "-"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
